sudo: required

language: go

go: 
  - "1.10.3"

go_import_path: github.com/go-park-mail-ru/2018_2_codeloft

branches:
  only:
    - master


services:
  - docker

before_install:
  - docker build --build-arg USERNAME=$USERNAME --build-arg PASSWORD=$PASSWORD .

script:
  - go test -v
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter ./...

after_success:
  - chmod +x ./to_machine_deploy.sh
  - ./to_machine_deploy.sh
