sudo: required

language: go

go: 
  - "1.10.3"

go_import_path: github.com/go-park-mail-ru/2018_2_codeloft

branches:
  only:
    - master
    - testing
addons:
  apt:
    packages:
      - sshpass

services:
  - docker

before_install:
  - docker build --build-arg USERNAME=$USERNAME --build-arg PASSWORD=$PASSWORD .
  - chmod +x ./to_machine_deploy.sh

script:
  - go test -v
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - gometalinter ./...

deploy: 
  provider: script
  script: bash to_machine_deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^testing|master$