sudo: required

language: go

go: 
  - "1.10.x"
  - "1.11"

services:
  - docker

before_install:
  - docker build .
  - go get github.com/go-park-mail-ru/2018_2_codeloft/database

script:
  - go test -v