version: '3'
services:
  api:
    env_file:
      - .env
    #network_mode: host
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3000:8080"
    environment:
      USERNAME: ${USER_NAME}
      PASSWORD: ${PASSWORD}
      ENV: "production"
    depends_on:
    - db
    - auth
#    - mongodb
#    links:
#    - db
#    networks:
#    - backend
  auth:
    env_file:
    - .env
    #network_mode: host
    restart: always
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    environment:
      USERNAME: ${USER_NAME}
      PASSWORD: ${PASSWORD}
      ENV: "production"
    depends_on:
    - db
#    links:
#      - db
#    networks:
#      - backend
  db:
    env_file:
    - .env
    #network_mode: host
    image: postgres
    restart: always
    ports:
    - "5432:5432"
#    expose:
#      - "5432"
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: codeloft
  
  # Prometheus
  prometheus:
    image: prom/prometheus
    volumes:
       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:Z
    #volumes:
    #- ./prometheus/:/etc/prometheus/
    #- prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  node_exporter:
    image: prom/node-exporter
    #volumes:
    #- ./prometheus/:/etc/prometheus/
    #- prometheus_data:/prometheus
    ports:
      - 9100:9100
    restart: always
#    networks:
#    - backend
#  mongodb:
#    env_file:
#    - .env
#    #network_mode: host
#    image: mongo
#    restart: always
#    ports:
#    - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
#      MONGO_INITDB_DATABASE: codeloft
#networks:
#  backend:
#    # Use a custom driver which takes special options
#    driver: "bridge"